GithubTransferRepos/Models/ErrorViewModel.cs
namespace GithubTransferRepos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GithubTransferRepos/Models/GitHubRepositoryModel.cs
namespace GithubTransferRepos.Models
{
    public class GitHubRepositoryModel
    {
        public string Name { get; set; }
        public bool IsSelected { get; set; }
        public long Id { get; set; }
    }

    public class GitHubSourceDestinationViewModel
    {
        public List<OwnerRepositoryModel> OwnerRepositoriesList { get; set; }
        public List<string> DestinationOwners { get; set; }
    }

    public class OwnerRepositoryModel
    {
        public string OwnerName { get; set; }
        public string OwnerAvtarUrl { get; set; }
        public List<GitHubRepositoryModel> Repositories { get; set; }
    }

    public class TransferRequestViewModel
    {
        public object OwnerName { get; set; }
        public object Repositories { get; set; }
    }

}

GithubTransferRepos/Controllers/GitHubController.cs
using GithubTransferRepos.Models;
using Microsoft.AspNetCore.Mvc;
using Octokit;

namespace GithubTransferRepos.Controllers
{
    public class GitHubController : Controller
    {
        private readonly GitHubClient _gitHubClient;
        private const string sourceRepo = "";
        private const string destinationRepo = "";
        private const string token = "";

        public GitHubController()
        {
            // Initialize GitHubClient with your Personal Access Token (replace "your-token" with your actual token)
            _gitHubClient = new GitHubClient(new ProductHeaderValue(sourceRepo));
            _gitHubClient.Credentials = new Credentials(token);
        }

        public async Task<ActionResult> Index()
        {
            // Retrieve repositories from authenticated user
            var repositories = await _gitHubClient.Repository.GetAllForCurrent();

            var owners = repositories.GroupBy(x => x.Owner.Login)
                             .Select(group => new OwnerRepositoryModel
                             {
                                 OwnerName = group.Key,
                                 OwnerAvtarUrl = group.First().Owner.AvatarUrl, // Fetch the AvatarUrl from the first repository in the group
                                 Repositories = group.Select(repo => new GitHubRepositoryModel
                                 {
                                     Id = repo.Id,
                                     Name = repo.Name,
                                     IsSelected = false,
                                 }).ToList()
                             }).ToList();

            //var viewModel = new GitHubSourceDestinationViewModel
            //{
            //    OwnerRepositoriesList = owners,
            //    DestinationOwners = repositories.GroupBy(x => x.Owner.Login).Select(x => x.Key).ToList()
            //};

            var list = repositories.Select(repo => new GitHubRepositoryModel
            {
                Name = repo.Name,
                IsSelected = false
            }).ToList();

            return View(list);
        }

        [HttpPost]
        public async Task<ActionResult> Transfer(List<GitHubRepositoryModel> repositories)
        {
            await TransferRepositories(repositories);
            ViewBag.success = true;
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private async Task TransferRepositories(List<GitHubRepositoryModel> repositories)
        {
            try
            {
                var selectedRepos = repositories.Where(repo => repo.IsSelected).Select(repo => repo.Id).ToList();

                // Transfer each selected repository to organization
                foreach (var id in selectedRepos)
                {
                    await _gitHubClient.Repository.Transfer(id, new RepositoryTransfer(destinationRepo));
                }
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
            }
        }
    }

}

GithubTransferRepos/Views/GitHub/Index.cshtml
@model List<GitHubRepositoryModel>

@using (Html.BeginForm("Transfer", "GitHub", FormMethod.Post))
{
    <table>
        <tr>
            <th>Repository Name</th>
            <th>Select</th>
        </tr>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].Name</td>
                <td>
                    @Html.HiddenFor(m => m[i].Id) <!-- Add hidden field for Id -->
                    @Html.CheckBoxFor(m => m[i].IsSelected)
                </td>
            </tr>
        }
    </table>
    <input type="submit" value="Transfer Selected Repositories">
}

GithubTransferRepos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GithubTransferRepos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/img/logo.jpg" alt="Logo" width="27" height="27" class="d-inline-block align-top" />

                <a class="navbar-brand" href="/Home">
                    <span style="background-color: black;color: white;padding-right: 5px;padding-left: 5px;">Transfer</span>
                    <span style="background-color: orange;padding-right: 5px;padding-left: 5px;">Hub</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Github" asp-action="Index">Github</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" id="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TransferHub
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>